export {default as Navbar} from './Navbar.jsx'
export {default as Hero} from './Hero.jsx'
export {default as New} from './New.jsx'
export {default as ClothingStyles} from './ClothingStyles.jsx'
export {default as Footer} from './Footer.jsx'